### ISSUE TITLE
linkResolver example

### ISSUE THREAD

**Issue by mathiasha** [angeloashmore/gatsby-source-prismic#125]
Hi 

I need some help setting up the linkResolver.
I find the documentation a bit hard to understand and the link to prismic documentation isn't much help either.

Can someone provide an example, including how to use it in a template.

**Comment by angeloashmore** [comment]
Hi @mathiasha, sure, I'll try to explain how it works.

The link resolver function is used to determine the URL for a particular Prismic document. Since Prismic allows you to construct the shape of your documents (i.e. the fields, names, etc.), Prismic has no notion of how the URL should be determined.

The link resolver function receives the document's data as an object and should return the document's URL as a string.

For example, if I have a blog post with a UID field with the value "my-first-blog-post", my link resolver function might look like this:

```js
// A typical Prismic link resolver function:
const linkResolver = doc => {
  // If the document is a BlogPost custom type:
  if (doc.type === 'blog_post') return `/blog/${doc.uid}`

  // Otherwise:
  return `/${doc.uid}`
}
```

This would return a URL of `/blog/my-first-blog-post` for that blog post.

Note that this is a core Prismic feature and not something special to this Gatsby source plugin.

The only different this plugin makes is also providing some Gatsby data to the link resolver. This is done by wrapping the function in another function. Sounds a little strange but the implementation is straightforward.

```js
// The same link resolver function as above, but for gatsby-source-prismic:
const linkResolver = ({ field, value, node}) => doc => {
  // If the document is a BlogPost custom type:
  if (doc.type === 'blog_post') return `/blog/${doc.uid}`

  // Otherwise:
  return `/${doc.uid}`
}
```

Note the `({ field, value, node}) =>` addition to the first line. This additional data allows you to customize the link resolver for based on the specific field that needs the URL, the value of that field, and the node containing the field. I personally don't use the `field`, `value`, or `node` data, but it is provided in case you need it.

Hope that helps, but let me know if you have further questions!

**Comment by mathiasha** [comment]
Thanks for that.
I still have one more question. How do I use the link?
What do I write in the template to use the link provided by the link resolver?

**Comment by mathiasha** [comment]
Actually i think i get it now. I was using providing uid (from this example https://www.gatsbyjs.org/docs/sourcing-from-prismic/) to the links rather url. It makes sense now.

**Comment by brybeecher** [comment]
This has confused me as well. Correct me if I'm wrong (@angeloashmore) but `gatsby-source-prismic` handles all this internally? ie. you don't have to use things like the RichText component from `prismic-reactjs` or the lower level `prismic-dom`, but the html content from the graphql layer has already been processed in this way?
