### ISSUE TITLE
- Unknown field 'data' on type 'PrismicAllDocumentTypes'

### ISSUE THREAD

**Issue by chapster11** [angeloashmore/gatsby-source-prismic#147]
I've been getting this error 

> Unknown field 'data' on type 'PrismicAllDocumentTypes.

 in a few files now and I'm seeing a fix to it in ___graphql by spreading the custom type. So here is what I had in V2 of the plugin. 
All I had to do was document.data

```
{
  prismicSupportHome {
    uid
    data {
      group {
        name
        category {
          uid
	 document {
            data {
              group {
                article {
                  uid
                }
              }
            }
          }
        }
      }
    }
  }
}
```
For V3 I now have to spread linked document type to get it to stop throwing the error above
Why is this and why is it necessary now to spread the linked content type ?

```
{
  prismicSupportHome {
    uid
    data {
      group {
        name
        category {
          uid
	 document {
            ... on PrismicSupportCategory {
              data {
                group {
                  article {
                    uid
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by angeloashmore** [comment]
@chapster11 I'm going through older issues now so I apologize for the late response!

Spreading on `document` fields was always in the recommended approach in `v2`: https://github.com/angeloashmore/gatsby-source-prismic/tree/19555979b1ff026aa58a9d64342496f2e33ef82b#query-content-relation-fields

Gatsby allowed omitting the spreading since it returned an array, but this is no longer the case; the query will return the document directly, without an array. The array method was more of a hack than anything to allow multiple types on a single field.

With Gatsby's new schema customization, we can do it properly in the GraphQL way. This requires spreading to tell GraphQL what type your fields are from.
