### ISSUE TITLE
Getting document uid of a parent document in linkResolver 

### ISSUE THREAD

**Issue by chapster11** [angeloashmore/gatsby-source-prismic#156]
I have 3 different documents that are been generated dynamically in Gatsby. In my link resolver I'm trying to get access to the parent uid of the linked document but not sure if this is possible. I've been looking into fetchLinks: [] as a possible option but so far I can only get that to show extra data in the doc you are in not the parent. 

Example: 
**support_category** 
  - uid
 - group 
   - linked document ( article )

**article**
  - uid

**My Resolver** 
```
  linkResolver(doc) {
    if (doc.type === 'support_home') {
      return '/support';
    } else if (doc.type === 'support_category') {
      return `/support/${doc.uid}`;
    } else if (doc.type === 'support_article') {
        return `/support/${doc.data.uid}/${doc.uid}`;
    }
    return doc.uid ? `/${doc.uid}` : '/';
  },
```

I tried using  fetchLinks: ['support_category.uid'],
but that doesn't seem to be working as my understanding of fetchLinks doesn't give me parent linked fields ?

This is the line i'm trying to build the url. 
    return `/support/${**parent-category**.uid}/${doc.uid}`;

**Comment by angeloashmore** [comment]
For your specific use case, I would typically structure the fields a bit differently. Rather than having a Support Category maintain a list of articles, I would go the other way: each Article would have a link field named `support_category` that links to a Support Category.

With that setup, you could just access that field to get the UID.

If you need to access additional content from the category, such as a title, you will need to use `fetchLinks`. Note that without `fetchLinks`, you still have access to the UID and type of the link. To get the linked Support Category data, you could use a fetchLinks like this:

```js
{
  fetchLinks: ['article.support_category'],
}
```

**Comment by chapster11** [comment]
Thanks @angeloashmore unfortunately the structure is already written and a lot of files depend on it, so i'm kind of locked in to the structure for now. I'll take that is there is no way to use the structure I have with fetchLinks then.

Right now support_home has a group of linked documents called support_category. Then support_category has the same setup with a group of linked Articles. 

I guess I could build a mapper function to try and figure out the mapping,  just thought there might be an easier solution. Thanks again for your help.

**Comment by angeloashmore** [comment]
Yup, I'd go with the mapper approach. 👍
