### ISSUE TITLE
shouldNormalizeImage what it does? 

### ISSUE THREAD

**Issue by giacomoalonzi** [angeloashmore/gatsby-source-prismic#159]
Hello guys, 
sorry for the question but I just wanna know shouldNormalizeImage what it does?

I mean can be used to retrieve the [processed and optimized images from prismic](https://prismic.io/blog/prismic-image-optimization-imgix) to pass down directly to gatsby-images and remove any processing on our side from the equation? 

Thanks :)

**Comment by angeloashmore** [comment]
Hi @giacomoalonzi, `shouldNormalizeImage` is a function that determines if a particular image is downloaded and made available to `gatsby-transformer-sharp` (this allows `gatsby-image` support).

This is done without the new imgix image processing.

I plan to support gatsby-image using imgix instead of gatsby-transformer-sharp, which should decrease build times significantly. It will be a while until support for this is available, however, as I have been quite busy lately.

Hope that answers your question 👍

**Comment by giacomoalonzi** [comment]
OK @angeloashmore thank you!
