### ISSUE TITLE
v2 slices: Fragment cannot be spread here as objects of type can never be of type

### ISSUE THREAD

**Issue by jenkshields** [angeloashmore/gatsby-source-prismic#186]
Kia ora!

I just ran into an issue with querying slices. Everything was working fine when I had one content type using slices, but as soon as I added them to the second I started getting these errors:

`There was an error in your GraphQL query:`

`Fragment cannot be spread here as objects of type "PrismicEssayBody1BlockquotePrismicEssayBody1TextUnion" can never be of type "PrismicBlogBody1CustomEmbed".`

`File: src/templates/blog.js:121:11`

My blog (the first content with slices) query looks like:

`body1 {
          ... on PrismicBlogBody1CustomEmbed {
            primary {
              embed {
                text
              }
            }
            slice_type
          }
          ... on PrismicBlogBody1Text {
            primary {
              text {
                html
              }
            }
            slice_type
          }
          ... on PrismicBlogBody1Blockquote {
            primary {
              quote {
                html
              }
            }
            slice_type
          }
        }`

And the essay query looks the same (but without a custom embed slice). 

For some reason the blog page seems to be trying to access the essay slices - as a union, maybe? - I'm not sure what's happening here! Any help greatly appreciated!

**Comment by jenkshields** [comment]
Figured this out - I think because I've defined a custom interface in gatsby-node, slice zones in prismic can't share names - both the blog and essay slice zones had api ids of Body1 so they shared slices somehow. After updating those the queries run fine again! Unsure if this is intended behavior or not, though.

**Comment by angeloashmore** [comment]
Hi @jenkshields, sorry for the late reply. Glad you figured a fix out!

The types should automatically be namespaced by their custom type and slice zone ID. I have not worked with v2 in a while since v3 has been in development for some time, but I wonder if it has something to do with the inferred types.

V3 replaces the inferred types for explicitly defined types using your custom type schemas, so this likely is solved there. If you have time, I recommend upgrading to V3. 👍
