### ISSUE TITLE
Access _allDocuments?

### ISSUE THREAD

**Issue by jenkshields** [angeloashmore/gatsby-source-prismic#193]
Is it possible for this plugin to expose the allDocuments operation in [Prismic's GraphQL API](https://prismic.io/docs/graphql/query-the-api/query-all-documents)? I'm trying to build a collated list of posts from various content types on a home page, but am having trouble composing a query to do so - being able to access every document would be incredibly helpful!

**Comment by angeloashmore** [comment]
Hi @jenkshields, all documents are fetched loaded into Gatsby using the document's type.

The easiest way to query all documents is to query all documents from each type. If you have a `page` and `blog_post` type, for example, your `AllDocuments` query would look like this:

```graphql
query AllDocuments {
  allPrismicPage {
    # The fields you need...
  }
  allPrismicBlogPost {
    # The fields you need...
  }
}
```

Then you would join those arrays into one.

Do note that if you run a query like this on a page, rather than in `gatsby-node`, you will be adding a large amount of data to your page. Limiting your query to the first _n_ nodes could be one way to limit the payload size.

**Comment by jenkshields** [comment]
Thanks so much for your help! I didn't even consider just merging those arrays - that was my last holdout to upgrading to v3, and I'm super grateful! I'm all set now, and with the new image processing my build times have gone from 5 minutes+ to under 2. Thanks so much for all your work!

**Comment by angeloashmore** [comment]
Awesome! Glad to hear it’s working well for you.
