### ISSUE TITLE
v3.0.0 - previewData and path returning undefined

### ISSUE THREAD

**Issue by kieranstartup** [angeloashmore/gatsby-source-prismic#205]
Hey,

I've just upgraded to 3.0.0 and I'm trying to implement Previews on my site following the guide here: https://github.com/angeloashmore/gatsby-source-prismic/blob/master/docs/previews-guide.md

I've copy and pasted the example code into my site, and the only thing I've changed in my `preview.js` file is the `repositoryName`. When I then try to preview a post in Prismic, my localhost preview opens as expected, but redirects to http://localhost:8000. I tried looking into the data returned and when I `console.log(isPreview)` it first returns `undefined` and then returns `true`.

But both `console.log(previewData)` and `console.log(path)`  return `undefined`.

I don't have any linkResolvers or pathResolvers set up on my site, but I've tried implementing these to see if it would fix the issue but my `previewData` and `path` still return `undefined`.

Let me know if I can provide anymore information.

Thanks!

**Comment by ahmedghazi** [comment]
I had the issue, try to test the data in useEffect before navigate
`if (isPreview === false 
      || isPreview === undefined
      || previewData === undefined 
      || path === undefined) return`

**Comment by angeloashmore** [comment]
Hi @kieranstartup, sorry for the late reply. @ahmedghazi is correct, you will only want to navigate if `isPreview` is `true` and `isLoading` is `false` (I just realized we need to update that example in the guide to reflect this). You don't necessarily need to check that `previewData` and `path` have values, however.

It's likely that `path` is undefined in your case since you aren't providing a link resolver. You should be giving the same link resolver to both `gatsby-node.js` and `usePrismicPreview`.

**Comment by angeloashmore** [comment]
Closing this out to clean up issues but feel free to continue this discussion if you're still having trouble.

**Comment by kieranstartup** [comment]
Hey @angeloashmore, sorry for my delay in getting back to you. I've just tested out @ahmedghazi fix above, and implemented a linkResolver in my Preview page and everything is working correctly now.

Thanks for your help!

**Comment by angeloashmore** [comment]
Awesome!
