### ISSUE TITLE
GraphQL error unknown field

### ISSUE THREAD

**Issue by NikitaSpirit** [angeloashmore/gatsby-source-prismic#21]
Hello!
I have a website built with Gatsby and i use gatsby-source-prismic package to get data from prismic.io. Everything works fine but when i delete image from content on prismic and rebuild project i get an error:
"GraphQL Error There was an error while compiling your site's GraphQL queries.
Invariant Violation: GraphQLParser: Unknown field `parameters_image` on type `data_2`"

Is there any way to make image data on prismic optional or something like that?
Because i need to be able to run my project even if some fields on prismic are empty

**Comment by angeloashmore** [comment]
Hey @NakitaSpirit, good question. Since Gatsby automatically creates a schema using the provided node/JSON, which does not include that field in this case, Gatsby does not know about that image field. GraphQL throws an error that the field doesn’t exist to let you know you may have mistyped something.

Check out this Gatsby issue where others have the same issue: https://github.com/gatsbyjs/gatsby/issues/2392

Unfortunately, this is a Gatsby/GraphQL error and is outside the scope of this plugin.

One suggestion from that link above is to create one dummy Document that contains the minimal amount of fields. This forces Gatsby to add the field to the schema, even if other Documents don’t contain the field.

**Comment by angeloashmore** [comment]
Closing this issue as there has not been activity for a while. Let me know if you're still running into this issue. 👍
