### ISSUE TITLE
Using Gatsby's Link with Prismic's Rich Text

### ISSUE THREAD

**Issue by imjamesdotme** [angeloashmore/gatsby-source-prismic#241]
Hey 👋

Apologises if this has been asked elsewhere but I'm struggling to find any information on it and looking for some clarity. 

I have a scenario where I'm currently getting some Rich Text from a slice and rendering it inside a component using React's `dangerouslySetInnerHTML` prop due to it the HTML already being parsed by prismic-dom as mentioned in the docs. 

I'd like to replace any internal links in the rich text with Gatsby's Link. However I wanted to check about the best way to go around this, given there is a htmlSerializer defined in the config and the HTML has already been parsed by prismic-dom. Due to the processing happening on the Node site, I'm assuming I can't use the Gatsby Link in the serializer here.

I'm guessing one method would be with **prismic-reactjs**, using the `RichText` component and then setting up `htmlSerializer` or `serializeHyperlink` with Gatsby Link in order to get this to work.

Any help or advice would be greatly appreciated! 😄

**Comment by etabard** [comment]
Hi ! 

You could use raw instead of HTML with prismic-reactjs. That way you can customize everything and use Gatsby Link or/and Gatsby Image. You just need an htmlSerializer, see doc here : https://prismic.io/docs/reactjs/beyond-the-api/html-serializer

The other way around is to parse the HTML and map to DOM elements to React. See the discussion here : https://github.com/angeloashmore/gatsby-source-prismic/issues/90#issuecomment-480419506

Hope it solves your issue !

**Comment by angeloashmore** [comment]
Hi @imjamesdotme,

Yep, @etabard's suggestion is a common way to do this. There are a couple other ways to do it depending on your priorities.

1. **[`gatsby-plugin-catch-links`](https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/) + `dangerouslySetInnerHTML`**

   `gatsby-plugin-catch-links` sets up a click handler for all `<a>` elements. When a click is detected, it intercepts the click and uses Gatsby's `navigate` function if the link is internal, just like `<Link>`. This is a CMS-agnostic approach (i.e. it will work for other source types, like Markdown or WordPress).

1. **[`prismic-reactjs`](https://github.com/prismicio/prismic-reactjs)**

   Like @etabard described above, you can use the `raw` field on Rich Text and Title fields. The value of `raw` can be passed into `prismic-reactjs` along with an HTML serializer containing your React component. This has the side-effect of coupling your components with Prismic, however.

1. **[`react-html-renderer`](https://github.com/angeloashmore/react-html-renderer)**

   Similar to `prismic-reactjs`, `react-html-renderer` accepts HTML, a map of HTML elements to React components, and renders it. The advantage of using this over `prismic-reactjs` is allowing your component to accept HTML rather than Prismic's proprietary Rich Text objects. This means the component is again CMS-agnostic.

I personally use the `react-html-renderer` approach as it allows flexibility in changing HTML elements into React components as needed while not coupling the system to Prismic. All three are valid approaches, however.

**Comment by angeloashmore** [comment]
I'm going to close this issue since there isn't a bug to track, but please feel free to reply here if you're having trouble setting it up. Thanks!

**Comment by imjamesdotme** [comment]
Hey @etabard @angeloashmore 👋 

Thank you both very much for your responses and information, greatly appreciate the help! I went with @angeloashmore's 3rd option, as for my requirements that makes the most sense.

@angeloashmore  Greatly appreciate the work you're doing on this pluing 👍 

Thanks again! 😄

**Comment by michaeljblum** [comment]
Where would you recommend using Gatsby's <Link> component to set up internal linking, @angeloashmore? As you point out, doing so in htmlSerializer doesn't yield the desired result. Doing so in linkResolver/gatsby-config doesn't seem to work either... 

Thanks for all your work and help!!!

**Comment by imjamesdotme** [comment]
Hey @michaeljblum  👋

I went with @angeloashmore's 3rd option above, using `react-html-renderer`. In case it's helpful, here's how I setup my Rich Text component and used Gatsby's `Link`. 

```
import React from "react"
import PropTypes from "prop-types"
import HTMLRenderer from "react-html-renderer"
import { Link } from "gatsby"
import { OutboundLink } from "gatsby-plugin-google-analytics"

import Heading from "../styled/Heading"

const externalUrlRegex = /https?:\/\/((?:[\w\d-]+\.)+[\w\d]{2,})/i

const RichText = ({ html }) => (
  <HTMLRenderer
    html={html}
    components={{
      h1: ({ name, ...props }) => {
        return <Heading as={name} {...props} />
      },
      h2: ({ name, ...props }) => {
        return <Heading as={name} {...props} />
      },
      h3: ({ name, ...props }) => {
        return <Heading as={name} {...props} />
      },
      h4: ({ name, ...props }) => {
        return <Heading as={name} {...props} />
      },
      a: ({ href, ...props }) => {
        if (externalUrlRegex.test(href)) {
          return (
            <OutboundLink
              data-link-type="external"
              href={href}
              target={props.target}
              rel={props.rel}
            >
              {props.children}
            </OutboundLink>
          )
        }
        return <Link data-link-type="internal" to={href} {...props} />
      },
    }}
  />
)

RichText.propTypes = {
  html: PropTypes.string.isRequired,
}

export default RichText
```

As you can see, I first check the `href` value to see if it's an internal or external link then proceed to return the nessessary component; if it's external I wrap it with `OutboundLink` and if it's internal, I wrap it with Gatsby's `Link`. For internal links the `href` value will be just the path e.g `/foo/bar` and for external links, it'll be the entire URL e.g `https://www.example.com`.

I hope this helps 😄
