### ISSUE TITLE
Provide HTML and raw content data node accessors

### ISSUE THREAD

**Issue by angeloashmore** [angeloashmore/gatsby-source-prismic#3]

**Comment by keighl** [comment]
#20 adds a raw data node. Providing serialized HTML fields is definitely possible but tricky because a) it's hard know which fields are HTML'able, and b) the user has to provide a [link resolver](https://prismic.io/docs/javascript/query-the-api/link-resolving) and an [HTML serializer](https://prismic.io/docs/nodejs/beyond-the-api/html-serializer).

I suppose the user could flag specific fields to serialize, though. And the plugin augments the schema with a `${fieldName}_HTML` node for each one.

```js
{
	resolve: `gatsby-source-prismic`,
	options: {
		repositoryName: process.env.PRISMIC_REPO,
		accessToken: process.env.PRISMIC_TOKEN,
	},
	preserializeHTMLFields: [
		'data.content',
		'data.body.authors.primary.author_bio' // slice e.g
	],
        linkResolver: ({ link_type, url, uid }) => {
		if (link_type === 'Page') {
			return `/pages/${uid}`
		}

		return data.url
	},
	htmlSerializer: (element, content) => {
		// No images allowed!
		if (element.type === 'image') { return '' }

		// Return null to use the default Prismic serializer implementation
		return null
	}
}

```

**Comment by angeloashmore** [comment]
@keighl Sorry for the very late response. I'm finally getting a chance to take a look at these issues.

I added basic support for `html`, `text`, and `raw` properties to RichText fields here: https://github.com/angeloashmore/gatsby-source-prismic/blob/01f7bc54d721069dba1550c081c26767a9b52aca/src/gatsby-node.js#L15-L21

I like your idea of providing a link resolver and HTML serializer in the config. The node could also be provided to the functions to allow for better control. And for specialized cases, the user could always query the data from `raw` and use `prismic-dom` directly.

**Comment by angeloashmore** [comment]
I think it makes sense to include both `raw` and `rawString`, similar to your PR #20 .

`raw` would allow a user to query specific fields using a standard declarative GraphQL query. Note that this allows Gatsby/GraphQL to perform some transformations on the data (e.g. removing null fields, transforming dates).

`rawString` would allow a user to perform `JSON.deserialize` on the JSON returned directly from `prismic-javascript` and use `prismic-dom` directly.

**Comment by angeloashmore** [comment]
Closing in favor of #24.
