### ISSUE TITLE
Question: Roadmap for v4

### ISSUE THREAD

**Issue by fredshevek** [angeloashmore/gatsby-source-prismic#305]
Hi @angeloashmore,

Thanks very much for the great work you keep doing on this project.
I've noticed there is a v4 branch and wondered if there is any roadmap somewhere?

The main reason I'm asking, I'm curious whether you are thinking of using https://github.com/imgix/gatsby in v4?

When I've started my project, I didn't have a consistent strategy for handling images and I've deferred that decision. I'm about to refactor those parts now and I'm wondering whether I should wait for the release or not.

**Comment by angeloashmore** [comment]
Hi @fredshevek, thanks for the support.

Good question about the v4 roadmap. I've been using v4 as a way to experiment with different ideas, which is why you'll see several different v4 branches. Things are starting to come together so now would be a good time to document the changes.

I'll write up a proper roadmap in a separate issue where feedback can be provided.

## Images

Specifically for images, the plan is to support the new [gatsby-plugin-image](https://github.com/gatsbyjs/gatsby/discussions/27950) API (currently in beta, but soon to be finalized).

- **`fluid` and `fixed`** - Imgix `gatsby-image` data

   Both `fluid` and `fixed` will continue to exist, albeit deprecated. A new `gatsbyImageData` field will be added that supports the `gatsby-plugin-image` API.

   `fluid` and `fixed` are created using [gatsby-plugin-imgix](https://github.com/WalltoWall/gatsby-plugin-imgix), which was the basis for the @imgix/gatsby repo you linked. @imgix/gatsby currently does not expose the field creators that are needed to integrate into Prismic-specific types, so I don't think it will be used in gatsby-source-prismic V4. I'll have to look into it more and maybe connect with @frederickfogerty, the developer of @imgix/gatsby.

- **`localFile`** - gatsby-transformer-sharp image data

   Since `localFile` effectively uses gatsby-transformer-sharp to create the GatsbyImage data, the current `fluid` and `fixed` fields will continue to exist, as well as the new `gatsbyImageData` field.

Ultimately, I would recommend any current or new projects to use the Imgix `fluid` or `fixed` fields as it is much more performant for builds and potentially at request-time.

If your project is primarily using `localFile` and the time to convert to `fluid` or `fixed` is not worth the effort, then I would recommend holding off on any image refactoring.

Once V4 is out with the new gatsby-plugin-image support, then I would recommend migrating all images to that API. The plan is to have full API parity with gatsby-transformer-sharp's `gatsbyImageData` field.

**Comment by fredshevek** [comment]
Thanks @angeloashmore, this helps a lot.

I wasn't aware of the [gatsby-plugin-image](https://github.com/gatsbyjs/gatsby/discussions/27950) and it seems it's tackling a couple of long waited issues, like proper lazy loading and Lighthouse scores. 

As always, appreciate your hard work on this project!

**Comment by frederickfogerty** [comment]
Hi there all, Fred from @imgix here 👋 we're still investigating supporting the new gatsby-plugin-image API, but I imagine we'll support it eventually. Also @angeloashmore, we're still committed to exposing those helpers for you! I'll report back here if I have any more information.

**Comment by angeloashmore** [comment]
Awesome, that's great to hear @frederickfogerty!

**Comment by angeloashmore** [comment]
@fredshevek V4 roadmap posted here: #307

**Comment by frederickfogerty** [comment]
Just wanted to leave a little update here - we're (I'm) actively working on gatsby-plugin-image support as we speak, we definitely plan on having this supported before GatsbyConf.

**Comment by angeloashmore** [comment]
That’s awesome @frederickfogerty, thanks!
