### ISSUE TITLE
Tags with linkResolver?

### ISSUE THREAD

**Issue by txprojects88** [angeloashmore/gatsby-source-prismic#361]
Hi! 

Is there anyway to use the tags of a document in linkResolver? Here is an example of what I was thinking, but can't seem to get to work.

Thanks in advance!

```const linkResolver = (doc) => {
  if (doc.tags === ['XYZTag']) {
    return `/example/${doc.uid}`
  }
  return '/'
}

module.exports = linkResolver

**Comment by angeloashmore** [comment]
@txprojects88 I see you closed this issue, but in case that was an accident:

You should be able to access tags for a document using `doc.tags`. Doing a comparison like `doc.tags === ['XYZTag']` will always return `false` since it is comparing two different objects, but you can check if `docs.tags` includes the tag you're looking for:

```javascript
if (docs.tags.includes('XYZTag')) {
  return `/example/${doc.uid}`
}
```

**Comment by txprojects88** [comment]
Thanks you!!!!

**Comment by angeloashmore** [comment]
Hi @txprojects88, it's possible the `tags` property on the document is undefined. That is unusual, but you could fix it with this:

```js
const linkResolver = (doc) => {
  if (doc.tags?.includes('XYZ')) {
    return `/XYZ/${doc.uid}`
  }

  if (doc.tags?.includes('XYZ2')) {
    return `/XYZ2/${doc.uid}`
  }

  return '/'
}

module.exports = linkResolver
```

Note the `?.` after `docs.tags`. This is called [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).
