### ISSUE TITLE
Community Question: CDN Rates and reducing usage.

### ISSUE THREAD

**Issue by jodiedoubleday** [angeloashmore/gatsby-source-prismic#370]
I'm getting super high CDN data usage from my site on Prismic, admittedly it is very image-heavy, so I'm looking at ways of cutting down this usage.

So am I right in thinking that if I change the `shouldDownloadImage` to `true` it will switch most of the CDN (image) usage to my hosting company?  (where I get a cheaper rate)

Would it be more beneficial to use the IMGIX transforms to serve images rather than Gatsby Image?

I'm also going to stop serving videos from Prismic.. which should massively cut it down.

Has anyone got any tips to reduce CDN usage?

**Comment by angeloashmore** [comment]
Hey @jodiedoubleday, that's correct. If your CDN usage is high due to images via Imgix, you can switch to using locally-processed images hosted on your host.

The processing time for image can be quite high, especially for an image-heavy site. Ensuring the Gatsby cache is persistent between builds will help here. If you are using a service like Netlify, be aware of build time limits (I believe Netlify is 15 minutes, but it's been a while since I've hit their limit so I'm not 100% sure).

If you are okay with the longer build times and will not hit build time limits on your continuous integration service, this would be a viable alternative.

Moving videos to a standalone video service should help for sure.

Otherwise, by using Gatsby, you're already minimizing your Prismic API use. Since API queries are only made a build time, and at most repositories only need to make 1-10 network requests, you shouldn't see significant bandwidth usage due to data fetching. Media usage is likely the primary reason for high bandwidth use.

In the next version of the Gatsby plugin, we will have a `localFile` field for media links. This works like the `localFile` field for images. With it, you can download files, like videos or PDF, directly to your filesystem to serve on your host. This is still in development, but we're hoping to publish a beta soon.

You can preview the documentation for this functionality here: https://github.com/angeloashmore/gatsby-source-prismic/tree/b03cdd47558997103a0806e4deb73a6fced04c15/packages/gatsby-source-prismic#query-media-fields

**Comment by jodiedoubleday** [comment]
Thank you @angeloashmore

Trying to use localfile images dies (i think because there are so many images) so I'll investigate a few more options and will definitely be moving videos until I can move to V4 🎉

**Comment by angeloashmore** [comment]
Yeah, processing images locally is very computationally expensive. If you're running into issues with it downloading or erroring, please let me know. If it's a matter of it taking too long to process, there isn't much we can do here except recommend using Imgix (at the expense of more bandwidth usage).

I'm going to close this issue, but we can continue the discussion here, or feel free to open a new one if you run into bugs during the process.
