### ISSUE TITLE
V4 - Link Resolver

### ISSUE THREAD

**Issue by jodiedoubleday** [angeloashmore/gatsby-source-prismic#379]
So far moving over to the new version has been fairly simple, with a few flipping between different doc (I'm looking at you gatsby-image) but all in all it's going smoothly...

Having a few issues with the link resolver though, while trying out the beta, pretty sure it's user error here...

**_gatsby-config.js_**
```
const linkResolver = require('./src/utils/linkResolver')

    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: process.env.GATSBY_PRISMIC_MAIN_REPOSITORY_NAME,
        linkResolver: () => (doc) => linkResolver(doc),
        schemas: {
          blogpost: require('./src/schemas/blogpost.json'),
          page: require('./src/schemas/page.json'),
        },
      },
    },
```

**_src/utils/linkResolver.js_**
```
export const linkResolver = (doc) => {
  if (doc.uid !== 'index' && doc.type === 'page') {
    return `/${doc.uid}`
  }

  if (doc.type === 'blogpost') {
    return `/blog/${doc.uid}`
  }

  return '/'
}
```

**_Error_**
```
(function (exports, require, module, __filename, __dirname) { export const linkResolver = (doc) => {
                                                              ^^^^^^
SyntaxError: Unexpected token 'export'
```

anyone able to help/advise?

**Comment by angeloashmore** [comment]
Hey @jodiedoubleday, thanks for giving the V4 beta a try. Glad to hear it's mostly going smoothly. There are a couple of things to change here:

**Link Resolver and HTML Serializer functions no longer need the extra `() =>`**
https://github.com/angeloashmore/gatsby-source-prismic/blob/beta/packages/gatsby-source-prismic/docs/migrating-from-v3-to-v4.md#remove-field-data-from-link-resolver-and-html-serializer-functions

```diff
-         linkResolver: () => (doc) => linkResolver(doc),
+         linkResolver: (doc) => linkResolver(doc),
```

**Files in `gatsby-node.js` need to be written in CommonJS format**
This requirement is present since `gatsby-config.js` runs in Node.js. Currently, Gatsby isn't suited for ESM yet, so you will nee d to write your Link Resolver file using `module.exports` rather than `export const`

```diff
- export const linkResolver = (doc) => {
+ module.exports = (doc) => {
    if (doc.uid !== 'index' && doc.type === 'page') {
      return `/${doc.uid}`
    }

    if (doc.type === 'blogpost') {
      return `/blog/${doc.uid}`
    }

    return '/'
  }
```

I'm going to close this issue as those fixes should make it work. If not, please feel free to re-open it or post here and I'll follow up.

Thanks!
