### ISSUE TITLE
Do you offer image links that are not hosted by Imgix?

### ISSUE THREAD

**Issue by dungle-scrubs** [angeloashmore/gatsby-source-prismic#394]
It looks like you're using only Imgix images on the customer domain `images.prismic.io`, but we're wondering if this is a feature that can be turned off and instead query non-imgix images that can be used with `@imgix/gatsby`?

These links [don't seem to play well](https://community.prismic.io/t/issues-with-querying-images-field-extension-arguments-must-be-provided-as-an-object/2847) with the plugin `@imgix/gatsby`  when we extend the `PrismicImageType` fields and therefore we can't take advantage of `gatsby-plugin-image` to generate a `srcset` and benefit from the rest of the its features.

**Comment by angeloashmore** [comment]
Hey @dungle-scrubs, can you describe your use-case a bit more? Do you want to continue using Imgix but without the "imgix.prismic.io" domain?

`gatsby-source-prismic` V3 allows you to use Imgix URLs for `gatsby-image` (not `gatsby-plugin-image`), which includes automatic `srcSet` generation. You can also choose to use the `localFile` field to download the image and serve it from your own host.

`gatsby-source-prismic` V4, [currently in beta](https://github.com/angeloashmore/gatsby-source-prismic/issues/377), allows you to use Imgix URLs for `gatsby-plugin-image`. The plugin uses `@imgix/gatsby` underneath to create the `gatsbyImageData` fields. You will not need to extend the plugin's types with `@imgix/gatsby` if you want to use Imgix images.

**Comment by dungle-scrubs** [comment]
Hey @angeloashmore ,

Thanks for the info, and definitely looking forward to v4 :) 

To add a bit more context, our entire workflow revolves around sourcing data in such a way that images can be consumed by `gatsby-plugin-image` via the `gatsbyImageData` object, maintaining consistency across all images. When using `@imgix/gatsby`, it allows us to generate `gatsbyImageData` after defining which GraphQL fields to target and the image url source field to use.

However, when we configure `@imgix/gatsby` to create that `gatsbyImageData` object on the field `PrismicImageType`, it technically does work, but throws errors like this:

```
Field extension arguments must be provided as an object. Received "SEARCHABLE" on `PrismicImageFixedType.base64`.
```

Until `gatsby-source-prismic` v4 is released, we're hoping there's a way to retrieve an image src url from Prismic that  has not been modified by Imgix, so we can run it through `@imgix/gatsby`.  After taking a look at [this article](https://community.prismic.io/t/image-optimization-service-faq/5426), it says that when removing all parameters on the image url, Prismic will deliver the full original image.

However, we haven't been able to figure out how to do that because it seems like Prismic always wants to add `auto` `format` and `compress` by default.

I think if we could successfully remove all parameters when `gatsby-source-prismic` is configured, that might solve our problem until v4 is released.

Does that make sense?

**Comment by angeloashmore** [comment]
Hey @dungle-scrubs, yes, I think that all makes sense to me.

To answer your question directly: No, Prismic does not offer links that not hosted by Imgix (i.e. all Prismic images come from Imgix).

Removing all URL parameters may result in unintended effects. If you use the image cropping feature in Prismic, for example, you will lose that information. Image cropping is done by setting a `rect` URL parameter on the image URL.

If this is okay with you, you can remove all URL parameters using the following configuration object for `@imgix/gatsby`:

```js
// PrismicImageType
{
  nodeType: "PrismicImageType",
  fieldName: "imgixImage",
  getURL: field => {
    if (field.url) {
      const url = new URL(field.url)

      return `${url.origin}/${url.pathname}`
    }
  }
}
```

You can take the existing image URL from Prismic and reconstruct it, leaving off the URL parameters.

Re: the "Field extensions arguments" warning, this is something I've seen before when reloading the GraphQL data and schema. As the warning does not affect the functionality of the plugin, it should be safe to ignore it for now. As mentioned, V4 uses `@imgix/gatsby` to implement `gatsby-image` and `gatsby-plugin-image` functionality, so that error *should* go away.

**Comment by dungle-scrubs** [comment]
Thanks, this is just what we need while looking forward to v4.

**Comment by angeloashmore** [comment]
Great, glad to hear it's working! I'm going to close this issue but feel free to reply back if you run into issues.

**Comment by robclancy** [comment]
> However, we haven't been able to figure out how to do that because it seems like Prismic always wants to add auto format and compress by default.

I've been wasting so much time trying to figure out how to stop that, the image quality is so bad.
