### ISSUE TITLE
[v4] Preview error on some web browsers : `No type for path`

### ISSUE THREAD

**Issue by benjaminwaterlot** [angeloashmore/gatsby-source-prismic#396]
Hi @angeloashmore,

Thanks for your work on `gatsby-source-prismic`, it's a pleasure to work with :)

I've got a mysterious error on preview mode and would need your help to understand it: 

<img width="1992" alt="Screenshot 2021-06-16 at 09 35 42" src="https://user-images.githubusercontent.com/32556322/122178273-b7d41080-ce86-11eb-9dcd-80b08a5dbe0c.png">

## Stack

* Built and deployed on Gatsby Cloud + Gatsby Hosting,
* `gatsby-source-prismic` is version `4.0.0-beta.15` (edit: updated to `4.0.0-beta.18`, nothing changed),
* We are using the Custom Types API integration to retrieve the types schemas automatically

## Situation

This error **only happens** on the preview mode of the **deployed version** of our website ([here](https://shinestaging.gatsbyjs.io/tarifs) if you need it) - I couldn't reproduce it locally (neither in a dev server, nor by building it locally).
I tried rebuilding and emptying cache with no success.

I've got some troubles understanding the meaning of this message, and am not comfortable enough with the functional programming style used in `proxyDocumentSubtree.ts` to understand this part of the code.

* What is this mysterious "path" : `65835afba98d019db2da6746b47aaf07` ?
* I understand that this error could happen if my code is not synced with the Prismic custom types, but by using the Custom Types API, everything should be in sync, right ?
* I can't reproduce it locally ; do you see any reason for it ?

**Comment by benjaminwaterlot** [comment]
**Update :** 

This error stops showing when we switch browsers for the preview (in my case, from Google Chrome to Firefox), so we're not blocked anymore.

For the record, I tried clearing the cache, cookies and everything with no success ; whereas my colleague didn't even have this problem in the first place.

Therefore this issue is now more of: 
* a _feature request to add a more precise error message_ when this kind of error happens,
* an information for you that this error can happen :)

**Comment by angeloashmore** [comment]
Hey @benjaminwaterlot, thanks for the detailed report. This is very helpful!

For some background on the error: The preview plugin reads a file that contains a mapping between your Prismic custom type fields to their type (e.g. "RichText" or "Image"). It does this to re-shape documents from the Prismic API into something that matches the Gatsby GraphQL API. It MD5 hashes the field names to hide your Custom Type fields so it is not exposed to users.

The MD5 hashing only happens in production (i.e. `process.env.NODE_ENV=production`). In development, you will see a full path for the field (e.g. "page > data > title").

Since the error only appears in production for you, and intermittently, it's possible the MD5 function is not always returning the same result for a given field name. Or the plugin isn't downloading the types file correctly.

---

Can you perform the following test on your local machine (not Gatsby Cloud)?

1. Run `NODE_ENV=development gatsby build` to build the site without production mode.
2. Run `gatsby serve`.
3. Preview a document from Prismic (you may need to add another preview URL to Prismic for `http://localhost:9000/preview`).

Are you able to recreate the error using this version of the build?

Next, can you re-try these steps, but with `NODE_ENV=production`? This will enable the MD5 hashing (this is done by default on Gatsby Cloud)

1. Run `NODE_ENV=production gatsby build` to build the site with production mode.
2. Run `gatsby serve`.
3. Preview a document from Prismic.

Are you able to recreate the error using this version of the build?

**Comment by benjaminwaterlot** [comment]
Hey @angeloashmore, thanks a lot for your answer.

I already had tried to replicate the error locally (both in `yarn dev` and `yarn build`, and I verified that `NODE_ENV` changes had no impact). So it seems tied with the execution environment on Gatsby Cloud, as strange as it seems.



However, following your answer, I completely **removed the MD5 hashing** (using `patch-package` to remove the `NODE_ENV` check after the package is installed).

**The error message then changed to `No type for path: page`**. 


`page` is the `id` of one of our Custom Types, and there is no clear reason why this error would happen - especially only when executed on Gatsby Cloud.

We fully use the "Custom Types API" (until now, I didn't even pass the `schemas` prop in `gatsby-config`).

<hr>

**Workaround**

So I figured I would try _to stop using this Custom Types API_, and here's what I did : 
* Use the `https://customtypes.prismic.io/customtypes` endpoint to retrieve all my custom types,
* Save them as `.json` files,
* Feed them to the `schemas` prop,
* Remove the `customTypesApiToken` to prevent the automatic use of the Custom Types API at build time.

**It seems to work**, as the preview is now functioning on all environments (I'm not fully confident given the randomness of the previous problem, but it really seems to be fixed).

Do you see a reason why the automatic retrieval of types may fail only in certain execution environments ?

**Comment by benjaminwaterlot** [comment]
I think I've got news :D

I found this line in the build :

```
verbose 11.748821172 gatsby-plugin-prismic-previews(shine) - Wrote type paths store to public/static/621f58b4cec4ad92fb044e46727a5683.json
```

So I went to see this JSON file on our deployed website:
https://shinestaging.gatsbyjs.io/static/621f58b4cec4ad92fb044e46727a5683.json

It was **not up-to-date**, and was missing my latest Custom Type, whether the one served on localhost:9000 was up-to-date. 
I cleared the cache by doing a force-refresh on this particular URL (a simple refresh didn't change anything, I guess because of server-side caching ? The .json request was marked as 200, so I suppose it can't be browser caching).

After this cache clearing, the preview started working again.
Cache problem would explain browser inconsistencies and having the problem only on online environments.



**@angeloashmore do you think setting up a correct cache policy can be done on the plugin side ?** 
I'm not very proficient on these subjects.

**Comment by angeloashmore** [comment]
@benjaminwaterlot Sorry for the delayed reply. This is great insight!

Gatsby itself cannot manage how the web server provides cached content/headers, but we can make sure the filename changes anytime a schema is updated. It currently only uses the repository name which is a mistake due to the assumption that the server will properly invalidate the cache (I believe services like Netlify will do this automatically, but we should make a universal solution).

I have to think a bit on how it can be implemented but I will report back once a fix is published. Thank you for the detailed analysis!

**Comment by angeloashmore** [comment]
Hey @benjaminwaterlot, can you try out the latest beta and test for this issue again? `gatsby-plugin-prismic-previews@v4.0.0-beta.19`

I wish I had thought of this sooner, but I changed the fetch function for that JSON file to effectively skip the browser's cache. This should solve the issue. If it doesn't, there's an extra level of ignoring the cache that we can try, but I want to try this version first.

**Comment by benjaminwaterlot** [comment]
Hey @angeloashmore, I'm updating right now and will keep you updated (I think I should encounter this error in the next two days, when I add a new custom type, if the error is still there).

Thanks for your answers! :)

**Comment by angeloashmore** [comment]
@benjaminwaterlot Thanks! I appreciate it!

**Comment by angeloashmore** [comment]
I'm going to close this as it should be fixed, but I can reopen it if the issue persists. Thanks!

**Comment by benjaminwaterlot** [comment]
Indeed - I can confirm that the error didn't happen again after the upgrade, thanks ! 🎉
