### ISSUE TITLE
[V4] Error on 'url' fields

### ISSUE THREAD

**Issue by danspratling** [angeloashmore/gatsby-source-prismic#402]
After upgrading to V4, I'm running into an issue where the "url" field on links is creating errors.

`GraphQLError: String cannot represent value: [function]`

As far as I can tell, the "link" field has been forced to work only for documents/internal media but does not allow strings - which are used to link to external documents.

Full error example:
<img width="505" alt="Screenshot 2021-07-05 at 21 48 43" src="https://user-images.githubusercontent.com/11349104/124516975-c608b300-ddda-11eb-89f7-e82509dd03e5.png">

This does seem to have been an issue previously too, with no (stated) resolution (though I have not run into this issue before): https://github.com/angeloashmore/gatsby-source-prismic/issues/284#issuecomment-725419961

**Comment by danspratling** [comment]
Resolved: @angeloashmore reached out over twitter and informed me of an error I was having.

I was getting a function error because I hadn't properly followed the upgrade instructions.

```
plugins: [
    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: 'repo',
-       linkResolver: () => (doc) => linkResolver(doc), 
+       linkResolver: (doc) => linkResolver(doc),  //remove the wrapping function
```

**Comment by angeloashmore** [comment]
Hey @danspratling, thanks for posting the solution! I understand the error is a bit cryptic.

Validating a function plugin option is tricky since we can't determine what the function returns without calling it. All we can test easily is that it is a function. The function could technically contain side-effects so currently the plugin does not call it to check that the function returns a string.

Hope that makes sense. Feel free to reach out if you have any other issues or questions. 👍

**Comment by valtism** [comment]
Thanks for posting @danspratling, saved me a _lot_ of headaches.
