### ISSUE TITLE
Rich text fields with image as first item are improperly normalized to image fields

### ISSUE THREAD

**Issue by mgburns** [angeloashmore/gatsby-source-prismic#52]
Here's an example API response fragment from Prismic for such a field:

```
"rich_text_field": {
  "type": "StructuredText",
  "value": [
    {
      "type": "image",
      "url": "http://image-url",
      "alt": null,
      "copyright": null,
      "dimensions": {}
    },
    {
      "type": "heading2",
      "text": "Heading 2",
      "spans": [ ]
    }
  ]
}
```

Here's the line that's doing it:
https://github.com/angeloashmore/gatsby-source-prismic/blob/master/src/normalize.js#L10

It's assuming the object will have a `spans` property, which the inline image does not.

**Comment by angeloashmore** [comment]
Yeah, we’ll have to do better detection of field types. The same issue happens with embeds in Rich Text fields.

I have been thinking about using the schemas from Prismic. I think they would have to be manually provided since I can’t find an API to retrieve custom type schemas.

**Comment by angeloashmore** [comment]
Yup, it could. I have to learn more about providing Gatsby a GraphQL schema (help, anyone?), but it would effectively allow us to tell Gatsby what fields exist, even if data isn't provided. This would be a huge help.

**Comment by laradevitt** [comment]
I just wanted to note that my workaround was to replace the StructuredText field with a Slice zone. In my case the repo belongs to a client which makes it difficult to ensure the field never starts with an image. 

Migrating the content will be a bit of a pain (it's an older repo), but fortunately the client is only interested in including text and image slices, so this simplifies things.

So far it seems to be working well enough. The only gotcha so far is that I have to disable image captions, since at least one caption would need to be populated in every Slice zone in order for the plugin to pick it up (pretty sure this is a known issue, but I'm unable to track down a link right now).

**Comment by angeloashmore** [comment]
Just to follow up on this, I started working on generating a GraphQL schema from the Prismic schema so we know for sure when a field is Rich Text.

Progress is in the `as/parse-schema` branch (so far just the foundation of the implementation).

**Comment by angeloashmore** [comment]
Closing this out as `v3` has been in open beta for a while now and solves this issue. Please give it a try if you haven't yet!
